<template>
    <h1>HOME</h1>
    <h3>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim praesent elementum facilisis leo. Imperdiet proin fermentum leo vel orci porta non pulvinar. Vel risus commodo viverra maecenas accumsan lacus. Eu scelerisque felis imperdiet proin. Amet porttitor eget dolor morbi non arcu risus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Libero id faucibus nisl tincidunt eget nullam non nisi. Nec ullamcorper sit amet risus nullam. Dolor morbi non arcu risus. Cras ornare arcu dui vivamus arcu. Consequat ac felis donec et odio pellentesque diam. Aliquam eleifend mi in nulla. Scelerisque fermentum dui faucibus in ornare quam. Enim lobortis scelerisque fermentum dui faucibus.

Quis vel eros donec ac odio tempor orci. Scelerisque viverra mauris in aliquam sem fringilla ut. Id donec ultrices tincidunt arcu non sodales neque. Maecenas sed enim ut sem. Nisi porta lorem mollis aliquam ut porttitor leo. Commodo odio aenean sed adipiscing. Arcu non sodales neque sodales. Enim ut sem viverra aliquet eget. At auctor urna nunc id cursus metus. Et malesuada fames ac turpis egestas. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Neque gravida in fermentum et sollicitudin. Varius sit amet mattis vulputate enim nulla. Egestas fringilla phasellus faucibus scelerisque eleifend. Vitae tempus quam pellentesque nec nam aliquam sem et. Amet facilisis magna etiam tempor orci. Vulputate enim nulla aliquet porttitor lacus. Congue quisque egestas diam in arcu cursus euismod quis.

Ut eu sem integer vitae. Mauris cursus mattis molestie a iaculis at. Interdum velit euismod in pellentesque massa placerat duis ultricies. Faucibus interdum posuere lorem ipsum dolor sit amet. Felis eget velit aliquet sagittis id consectetur. Elementum curabitur vitae nunc sed velit. Arcu odio ut sem nulla pharetra diam sit. Consequat id porta nibh venenatis cras sed. Nulla facilisi nullam vehicula ipsum a arcu cursus. Et netus et malesuada fames ac turpis. Phasellus vestibulum lorem sed risus ultricies tristique. Tincidunt augue interdum velit euismod in pellentesque. Arcu risus quis varius quam quisque id diam. Fringilla ut morbi tincidunt augue interdum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Viverra aliquet eget sit amet tellus. Tristique nulla aliquet enim tortor at auctor urna nunc. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Malesuada proin libero nunc consequat. Tristique risus nec feugiat in fermentum posuere urna.

Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Pulvinar elementum integer enim neque volutpat ac. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Tincidunt lobortis feugiat vivamus at augue eget arcu. Rhoncus dolor purus non enim. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Neque vitae tempus quam pellentesque nec nam. Risus sed vulputate odio ut enim blandit volutpat maecenas. Nunc aliquet bibendum enim facilisis gravida neque convallis a. Donec ultrices tincidunt arcu non. Nec ultrices dui sapien eget mi proin. Id neque aliquam vestibulum morbi blandit cursus. Quis imperdiet massa tincidunt nunc pulvinar sapien. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Diam volutpat commodo sed egestas. Pulvinar pellentesque habitant morbi tristique senectus et netus. Ullamcorper dignissim cras tincidunt lobortis. Mattis aliquam faucibus purus in massa tempor nec. Fringilla urna porttitor rhoncus dolor.

Nisi porta lorem mollis aliquam ut. Morbi tincidunt augue interdum velit euismod in. Et sollicitudin ac orci phasellus egestas. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Quam lacus suspendisse faucibus interdum posuere. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Augue mauris augue neque gravida in fermentum. Dui faucibus in ornare quam viverra orci. Augue mauris augue neque gravida in fermentum et sollicitudin. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Maecenas sed enim ut sem viverra aliquet. Odio tempor orci dapibus ultrices in. Ultrices eros in cursus turpis massa tincidunt. Aliquam sem fringilla ut morbi tincidunt augue interdum. Adipiscing commodo elit at imperdiet dui accumsan. Sollicitudin ac orci phasellus egestas tellus rutrum.

Volutpat consequat mauris nunc congue nisi vitae. Dictum at tempor commodo ullamcorper a lacus. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Molestie a iaculis at erat pellentesque. Ac orci phasellus egestas tellus rutrum. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Scelerisque purus semper eget duis at tellus. Suscipit tellus mauris a diam maecenas sed enim. Felis eget velit aliquet sagittis id consectetur purus. Non sodales neque sodales ut etiam sit. Id donec ultrices tincidunt arcu. Viverra ipsum nunc aliquet bibendum enim. Nascetur ridiculus mus mauris vitae ultricies. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed arcu non odio euismod. Nunc lobortis mattis aliquam faucibus purus in massa. A condimentum vitae sapien pellentesque habitant. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Malesuada bibendum arcu vitae elementum curabitur vitae. Orci eu lobortis elementum nibh tellus.

Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Massa id neque aliquam vestibulum morbi blandit cursus. Nec ultrices dui sapien eget mi proin sed libero. Adipiscing at in tellus integer feugiat scelerisque varius. Augue mauris augue neque gravida in fermentum et. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Amet justo donec enim diam. Scelerisque purus semper eget duis at tellus. Sed tempus urna et pharetra. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Aliquam id diam maecenas ultricies. Massa massa ultricies mi quis. Aliquam vestibulum morbi blandit cursus.

Amet nulla facilisi morbi tempus iaculis urna. At augue eget arcu dictum. Et egestas quis ipsum suspendisse ultrices gravida dictum. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Sapien eget mi proin sed libero. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Eu mi bibendum neque egestas. Dignissim cras tincidunt lobortis feugiat vivamus at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Cursus eget nunc scelerisque viverra mauris in. Ipsum dolor sit amet consectetur adipiscing elit ut. Scelerisque in dictum non consectetur a erat. Facilisi etiam dignissim diam quis enim. Pellentesque adipiscing commodo elit at. Mollis aliquam ut porttitor leo a diam. Nibh tortor id aliquet lectus proin nibh. Scelerisque fermentum dui faucibus in ornare. Integer enim neque volutpat ac tincidunt.

Arcu felis bibendum ut tristique et egestas. Velit aliquet sagittis id consectetur purus. Sit amet est placerat in egestas erat imperdiet sed euismod. Ullamcorper malesuada proin libero nunc consequat interdum. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Risus sed vulputate odio ut. Aliquam sem fringilla ut morbi. Enim tortor at auctor urna nunc id cursus. Aliquam ut porttitor leo a diam sollicitudin tempor. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Gravida in fermentum et sollicitudin. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Leo vel orci porta non. Tincidunt lobortis feugiat vivamus at augue eget. Blandit cursus risus at ultrices mi tempus. Vitae ultricies leo integer malesuada nunc.

Nibh tellus molestie nunc non blandit massa. Mauris ultrices eros in cursus turpis massa. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Integer vitae justo eget magna fermentum iaculis eu. Senectus et netus et malesuada fames ac turpis. Enim diam vulputate ut pharetra sit amet aliquam id diam. Porttitor eget dolor morbi non arcu risus quis varius quam. Eu mi bibendum neque egestas congue quisque. Auctor urna nunc id cursus metus aliquam. Neque viverra justo nec ultrices dui sapien eget. Varius quam quisque id diam vel. Bibendum at varius vel pharetra vel turpis nunc eget. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Consequat nisl vel pretium lectus quam id leo in vitae.

Ut sem nulla pharetra diam sit amet. Augue neque gravida in fermentum et. Lacinia at quis risus sed vulputate odio ut enim blandit. In est ante in nibh. Egestas fringilla phasellus faucibus scelerisque. Nascetur ridiculus mus mauris vitae ultricies. Ornare suspendisse sed nisi lacus. Eu facilisis sed odio morbi quis commodo odio. Sed velit dignissim sodales ut eu sem integer. Urna porttitor rhoncus dolor purus. Amet nisl purus in mollis nunc sed id.

Felis eget nunc lobortis mattis. Convallis posuere morbi leo urna molestie. Vitae tortor condimentum lacinia quis vel eros donec ac odio. Eget nunc scelerisque viverra mauris in. Metus vulputate eu scelerisque felis imperdiet proin. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Nibh mauris cursus mattis molestie a iaculis. Eu volutpat odio facilisis mauris. Et magnis dis parturient montes nascetur. Ipsum dolor sit amet consectetur. Eu feugiat pretium nibh ipsum consequat nisl vel. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Posuere urna nec tincidunt praesent. Porttitor leo a diam sollicitudin tempor.

Aenean euismod elementum nisi quis eleifend quam. Neque viverra justo nec ultrices dui sapien. Id faucibus nisl tincidunt eget nullam non. Proin sagittis nisl rhoncus mattis rhoncus urna. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Auctor urna nunc id cursus metus. Viverra mauris in aliquam sem. Amet mauris commodo quis imperdiet massa tincidunt. Diam maecenas sed enim ut sem viverra aliquet eget sit. Odio facilisis mauris sit amet massa vitae. Arcu odio ut sem nulla pharetra diam sit. Facilisis mauris sit amet massa vitae tortor condimentum. Quis blandit turpis cursus in hac habitasse platea. Fames ac turpis egestas sed tempus urna et pharetra pharetra. Viverra tellus in hac habitasse platea. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Lorem ipsum dolor sit amet consectetur. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Habitant morbi tristique senectus et netus et malesuada. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est.

Volutpat diam ut venenatis tellus in metus vulputate. Non diam phasellus vestibulum lorem sed risus ultricies. Aliquam etiam erat velit scelerisque in dictum non. Sit amet est placerat in egestas erat. Egestas pretium aenean pharetra magna. In est ante in nibh mauris. Scelerisque purus semper eget duis at tellus at urna condimentum. Elementum tempus egestas sed sed. Amet dictum sit amet justo donec enim diam. Augue lacus viverra vitae congue eu consequat.

Phasellus vestibulum lorem sed risus ultricies tristique nulla. Vitae purus faucibus ornare suspendisse sed nisi lacus. Amet nulla facilisi morbi tempus iaculis urna id. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Sed elementum tempus egestas sed sed risus pretium quam vulputate. Cursus metus aliquam eleifend mi in nulla posuere. Penatibus et magnis dis parturient. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Arcu cursus vitae congue mauris rhoncus aenean vel. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Turpis egestas sed tempus urna et pharetra pharetra. Eu consequat ac felis donec et odio.
</h3>
  </template>
  <style scoped>
  h1,h3{
    color:white;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif ; 
  }
  </style>